### ISSUE TITLE
Incorrect use of app key to request token

### ISSUE THREAD

**Issue by swouf** [graasp/graasp-app-sticky-notes#133]
The app cannot request a token properly. The app key seems to be missing.

<img width="1510" alt="Screenshot 2023-06-21 at 16 08 28" src="https://github.com/graasp/graasp-app-sticky-notes/assets/5767619/1b52aa1f-3027-4ba9-b26f-c06a961812bc">

**Comment by pyphilia** [comment]
This was because a renovate branch got deployed, the typeorm was not merged yet.
